### ISSUE TITLE
Submission Checklist

### ISSUE THREAD

**Issue by davidvaz77** [davidvaz77/git_assignment#1]
Submission checklist: 
- [x] Create a branch called assignment.
- [x] Ensure that the repository is public.
- [x] Review [the PR description guidelines] and adhere to them.
- [x] Verify that the link is accessible in a private browser window.

**Comment by davidvaz77** [comment]
[](https://github.com/davidvaz77/git_assignment/pull/2)
